title: Website Title

description: Website Description (goes in footer).

author:
  name: Site owner name
  email: site_owner@some_domain.com

github:
  owner_name: gh-owner
  repository_name: gh-repo
  source:
    branch: main

nav_pages:
  - index.md
  - about.md
  # - podcasts.md
  - contact.md

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  podcasts:
    output: true
    permalink: /:collection/:path/

show_excerpts: true
show_rss_feed: true
max-width: 1000px

footer:
  show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
